cyber: add missing include for mutex
* fixes:
ERROR: (09-30 16:48:12.240) /apollo/cyber/bridge/BUILD:5:1: C++ compilation of rule '//cyber/bridge:cyber_bridge' failed (Exit 1).
In file included from cyber/bridge/clients.cc:11:0:
./cyber/bridge/client.h:38:3: error: 'mutex' in namespace 'std' does not name a type
   std::mutex publish_mutex;
   ^

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>